version: '3'
services:
  bmgr:
    build:
       context: .
    ports:
     - "5432:5432"
    environment:
       DB_PASS: bmgrpass
       DB_USER: bmgr
       DB_HOST: db
    volumes:
      - ./confs:/etc/bmgr
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    volumes:
       - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: bmgrroot
       MYSQL_DATABASE: bmgr
       MYSQL_USER: bmgr
       MYSQL_PASSWORD: bmgrpass
volumes:
  db_data:
